# Adwaita Pastel Dark (fzf)

--border=rounded
--color=bg:#1e1e1e,bg+:#303030,fg:#c7c7c7,fg+:#ffffff,hl:#0ab9dc,hl+:#0ab9dc,info:#c7c7c7,prompt:#c7c7c7,pointer:#62a0ea,marker:#57e389,spinner:#0ab9dc,header:#808080,border:#4f4f4f,gutter:#1e1e1e,separator:#4f4f4f
