monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.50_1B_6A_86_FB_B4"
      }
    ]
    actions = {
      update-props = {
        bluez5.profile = "a2dp-sink"
        bluez5.auto-connect = [ "a2dp-sink" ]
      }
    }
  }
]
